### ISSUE TITLE
Can not show app bundle's info

### ISSUE THREAD

**Issue by cool8jay** [ealeksandrov/ProvisionQL#14]
After installing ProvisionQL, an app bundle's quick info is changed as this:

![screen shot 2017-11-06 at 8 28 32 am](https://user-images.githubusercontent.com/55504/32420893-d36f4a2c-c2cc-11e7-93a3-ec42b66defc2.png)

which should be like:

![screen shot 2017-11-06 at 8 28 06 am](https://user-images.githubusercontent.com/55504/32420894-d8204710-c2cc-11e7-90db-ca14aeaa0437.png)

Version and copyright info is gone.

Tried on 1.2.0 and 1.3.0.

**Comment by ealeksandrov** [comment]
Thanks for report, I confirmed it, will check.

**Comment by ealeksandrov** [comment]
Looks like `.app` or `com.apple.application-bundle` QL support indeed breaks something in macOS `.app` previews. For unknown reason. 

I decided to remove support for app-bundle preview altogether, since It's likely not used by users - app bundles are missing generated icons (lately or always?) and I see no reports :)

**Comment by ealeksandrov** [comment]
After some time spent on ProvisionQL and messing with bundles - I really want ".app" previews back :)
I will test again missing info on macOS apps previews and will submit rdar to Apple, since it's out of scope of ProvisionQL to fix.
