### ISSUE TITLE
Request to support xx.mobileconfig and xx.dmg

### ISSUE THREAD

**Issue by acalism** [ealeksandrov/ProvisionQL#39]

**Comment by ealeksandrov** [comment]
Hello @acalism, thanks for suggestions!

I don't see `mobileconfig` support is in line with ProvisionQL, since it's unrelated to apps provisioning process. I can see that [SourceCodeSyntaxHighlight](https://github.com/sbarex/SourceCodeSyntaxHighlight) supports it as XML, so you can try it.

`dmg` is a disc image format that frequently used to distribute macOS applications, but it can work with file content of any type. Since ProvisionQL doesn't support macOS `app` preview, we are not ready to expand with more containers.
